### PR TITLE
Add IgnoreProperty attribute to be able to ignore properties from sou…

### PR DESCRIPTION
**Pull request by tstanitz**
related issue #5

### CODE REVIEW

**Comment by tstanitz** [comment]
I am not very happy with the test but have no idea how to check that id property is not mapped

**Comment by tstanitz** [comment]
@RasicN what do you think about this change?

**Comment by peterdeme** [comment]
@RasicN

**Comment by RasicN** [comment]
I'll try and take a look today, sorry about that.

**Comment by tstanitz** [comment]
I just changed the email from my company to my private

**Review by RasicN — COMMENTED** [review]
Could we make the test verify that it is actually ignoring the Id attribute?

**Pull request merged**
